server:
  port: ${SERVER_PORT:8011}
  servlet:
    context-path: /api-speak/v1
    
grpc:
  server:
    port: ${GRPC_SERVER_PORT:8211}
    enableKeepAlive: true
    permitKeepAliveWithoutCalls: true
    keepAliveTime: ${GRPC_SERVER_KEEP_ALIVE_TIME:60}
    keepAliveTimeout: ${GRPC_SERVER_KEEP_ALIVE_TIMEOUT:20}
  client:
    grpc-server:
      address: ${GRPC_THIRD_PART_ADDRESS:localhost:8212}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      permitKeepAliveWithoutCalls: true
      keepAliveTime: ${GRPC_CLIENT_KEEP_ALIVE_TIME:60}
      keepAliveTimeout: ${GRPC_CLIENT_KEEP_ALIVE_TIMEOUT:20}
      negotiationType: PLAINTEXT

http:
  thirdPartAddress: ${HTTP_THIRD_PART_ADDRESS:http://localhost:8012/api-third-part/v1/authorize}

logging:
  file:
    name: api-speak.log
  level:
    root: ${LOGGING_LEVEL:info}
